environment:
  name: prod
  dns: prod.yacapai.com
client:
  name: frontend
  replicaCount: 1
  image:
    repository: biotux7/prod-js-frontend
    tag: 8a3d70e772b6b42448e3e7e100426f2f89965197
  deploymentPorts:
    containerPort: 3000
  servicePorts:
    port: 3000
    targetPort: 3000
  ingressPorts:
    port: 3000
backend:
  name: microservice
  replicaCount: 1
  image:
    repository: biotux7/prod-microservice
    tag: fdc8a21d380a07e1482f7e7eefdd5628cb724088
  deploymentPorts:
    containerPort: 5000
  servicePorts:
    port: 5000
    targetPort: 5000
  ingressPorts:
    port: 5000
  env:
    PGUSER: produser
    PGHOST: postgres-rds.cz0vpnsvjuwe.us-east-1.rds.amazonaws.com
    PGDATABASE: production
    PGPASSWORD: production
