name: CI/CD frontend service

on:
  push:
    branches:
      - dev
    paths:
      - 'react-node-app/frontend/**'
      - '!helm-react-node-app/**'
      - '!react-node-app/microservice/**'
      - '!.github/**'

jobs:

  apply_linter:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-node-app/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint

  build_prod_files:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-node-app/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: CI='' npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./react-node-app/frontend/build

  tests:
    needs: [apply_linter, build_prod_files]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-node-app/frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Test
        run: npm test

  build_and_push_image:
    needs: [apply_linter, build_prod_files, tests]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA)
          echo "::set-output name=sha::$SHA"

      - name: Build js-frontend docker image
        run: docker build -t biotux7/${{ github.ref_name }}-js-frontend:${{ steps.generate_sha.outputs.sha }} ./react-node-app/frontend
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Push js-frontend image
        run: |
          docker push biotux7/${{ github.ref_name }}-js-frontend:${{ steps.generate_sha.outputs.sha }}
          docker tag biotux7/${{ github.ref_name }}-js-frontend:${{ steps.generate_sha.outputs.sha }} biotux7/${{ github.ref_name }}-js-frontend:latest
          docker push biotux7/${{ github.ref_name }}-js-frontend:latest
          
      - name: Update js-frontend image helm
        uses: fjogeleit/yaml-update-action@master
        with:
          branch: dev
          valueFile: 'helm-react-node-app/values.yaml'
          propertyPath: 'client.image.tag'
          value: ${{ steps.generate_sha.outputs.sha }}
          commitChange: true
          updateFile: true
          message: "NEW: Update tag in frontend values helm"

